config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 4, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimun: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?

  def current_user
    #If there is a current user, it simply returns it, else it finds the current user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    #!! returns a boolean
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #Runs the method before anything else
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user_or_admin, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles  = Article.paginate(page: params[:page], per_page: 5).order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:notice] = "Article was created succesfully!"
      redirect_to @article 
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated succesfully!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user_or_admin
    if current_user !=  @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end
   
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "The category has been saved successfully"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_no_log_in, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:alert] = "Email or password were not found!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

  private
  def require_no_log_in
    if logged_in?
      flash[:alert] = "You have already logged in"
      redirect_to current_user
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :require_same_user_or_admin, only: [:edit, :update, :destroy]
  before_action :require_no_log_in, only: [ :new, :create]


  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5).order("created_at DESC")
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You signed up succesfully!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile was updated succesfully!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    session[:user_id] = nil if @user == current_user
    @user.destroy
    flash[:notice] = "Account and all associated articles have been deleted"
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user_or_admin
    if current_user !=  @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account!"
      redirect_to @user
    end
  end

  def require_no_log_in
    if logged_in?
      flash[:alert] = "You have already logged in"
      redirect_to current_user
    end
  end
      
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="container">
      <div class="card text-center shadow mb-5 bg-white rounded">

        <div class="card-header">
          by <%= link_to article.user.username, article.user%>
        </div>

        <div class="card-body">
          <h5 class="card-title">
            <%= link_to article.title, article_path(article), class: "tex-primary" %>
          </h5>
          <p class="card-text">
            <%= truncate(article.description, length: 100) %>
          </p>
          <%= link_to 'View', article_path(article), class: "btn btn-outline-primary" %>

          <% if logged_in? && (article.user_id == current_user.id || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to 'DELETE', article_path(article), method: :delete, class: "btn btn-outline-danger" %>
          <% end %>
        </div>

        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
        
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
  <body>
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/errors', obj: @article %>
        <%= form_with(model: @article, class: "shadow-lg p-3 mb-5 bg-darkgray rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label" %>
            <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow-sm rounded", placeholder: "Tile of Article"%>
            </div> 
          </div>

          <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_area :description, rows: 5, class: "form-control shadow-sm rounded", placeholder: "Description of Article"%>
            </div> 
          </div>

          <div class="container">
            <div class="form-group row justify-content-center">
              <%= f.submit class: "btn btn-light btn-lg shadow-sm rounded" %>
            </div>

            <div class="form-group row justify-content-center">
              <%= link_to 'Cancel', articles_path, class: "btn btn-dark btn-lg shadow-sm rounded" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</div>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form' %>
</body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">All Articles</h1>

  <% if logged_in?%>
    <div class="container" id="new-button-container">
      <div class="row justify-content-md-center">
        <div class="mt-4">
          <%= link_to 'NEW', new_article_path(), class: "btn btn-success btn-lg shadow-sm rounded"%>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'article' %>

  <div class="flickr_pagination md-4">
    <%= will_paginate @articles, :container => false %>
  </div>

  </body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Create a new Article</h1>
  <%= render 'form' %>
</body>
</html>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
  <div class="container">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header">
        by <%= link_to @article.user.username, @article.user %>
        <%= link_to gravatar_for(@article.user), @article.user %>
      </div>
      <div class="card-body">
        <div class="card-text">
          <%= simple_format(@article.description) %>
        </div>
        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to 'DELETE', article_path(@article), method: :delete, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(@article.created_at) %> ago,
          Edited <%= time_ago_in_words(@article.updated_at) %> ago
        </small>
      </div>
    </div>
  </div>
</div>
</div>

app/views/categories/_form.html.erb
<div class="container">
  <body>
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/errors', obj: @category %>
        <%= form_with(model: @category, class: "shadow-lg p-3 mb-5 bg-darkgray rounded", local: true) do |f| %>

          <div class="form-group row">
            <%= f.label :name, "Category name", class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :name, class: "form-control shadow-sm rounded", placeholder: "Type the name..."%>
            </div> 
          </div>

          <div class="container">
            <div class="form-group row justify-content-center">
              <%= f.submit "Create", class: "btn btn-light btn-lg shadow-sm rounded" %>
            </div>

            <div class="form-group row justify-content-center">
              <%= link_to 'Cancel', root_path, class: "btn btn-dark btn-lg shadow-sm rounded" %>
            </div>

          </div>
        <% end %>
      </div>
    </div>
  </body>
</div>

app/views/categories/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Create a new Category</h1>
  <%= render 'form' %>
</body>
</html>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1> 

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">    <%= link_to 'Luke Dias - Github', 'https://github.com/HollowLukeDias', class: "text-white" %>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container" id="message">
  <% flash.each do |name, message| %>
    <div class="alert alert-success  alert-dismissible fade show shadow-sm rounded" role="alert">
      <h3><%= message %></h3>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Alpha Rails Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" id="toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <% if logged_in? %>
            <li class="nav-item">
              <%= current_user.admin? ? (link_to "Admin ", current_user, class:"nav-link") : ""  %> 
            </li>

            <li class="nav-item">
              <%= link_to gravatar_for(current_user, size: 30), current_user, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to current_user.username, current_user, class:"nav-link" %>
            </li>
            
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class:"nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class:"nav-link" %>
            </li>
            <% end %>

          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class:"nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Articles', articles_path, class: "dropdown-item" %>
              <% if logged_in?%>
                <%= link_to 'New Article', new_article_path, class: "dropdown-item" %>
              <% else %>
              <%= link_to 'New Article', new_article_path, class: "disabled dropdown-item" %>
              <% end %>
            </div>
          </li>

        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="https://img.icons8.com/cute-clipart/64/000000/book.png" type="image/x-icon">
    <title>Blog on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="container" id="home-container">
    <div class="jumbotron text-white", id = "about-jumbotron">
      <h1 class="display-4">What is this webpage about</h1>
      <p class="lead">This is all about learning. Learning something new. Learn something exciting!</p>
      <p class="lead">Seriouly though. Hi, I am Lucas (aka Luke), and I love programming, I really love to face challenges and overcome them, it really is amazing</p>
      <p class="lead">And thus I am doing this application so I can learn more programming and get a job as a developer!</p>
    </div>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="container" id="home-container">
      <div class="jumbotron text-white" id ="home-jumbotron">
        <h1 class="display-4">Welcome to Blog on Rails</h1>
        <p class="lead">Here you are able to create articles and share them with everyone.</p>
        <hr class="my-4">
        <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %>
        <%= link_to "About", about_path, class: "btn btn-secondary btn-lg" %>
      </div>
    </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-warning alert-dismissible fade show shadow-sm rounded" role="alert">
  <h4 class="alert-heading">These errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul> 
    <% obj.errors.full_messages.each do |message| %> 
      <li><%= message %></li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <body>
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/errors', obj: @user %>
        <%= form_with(model: @user, class: "shadow-lg p-3 mb-5 bg-darkgray rounded", local: true) do |f| %>

          <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label" %>
            <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow-sm rounded", placeholder: "Enter a username"%>
            </div> 
          </div>

          <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.email_field :email, class: "form-control shadow-sm rounded", placeholder: "Enter your email address"%>
            </div> 
          </div>

          <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.password_field :password, class: "form-control shadow-sm rounded", placeholder: "Choose a password"%>
            </div> 
          </div>

          <div class="container">
            <div class="form-group row justify-content-center">
              <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-light btn-lg shadow-sm rounded") %>
            </div>

            <% if !@user.new_record? %>
              <div class="form-group row justify-content-center">
                <%= link_to "DELETE ACCOUNT", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg shadow-sm rounded" %>
              </div>
            <% end %>
            <div class="form-group row justify-content-center">
              <%= link_to 'Cancel', @user, class: "btn btn-dark btn-lg shadow-sm rounded" %>
            </div>

          </div>
        <% end %>
      </div>
    </div>
  </body>
</div>

app/views/users/_users.html.erb
<% @users.each do |user| %>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="container">
      <div class="card text-center shadow mb-5 bg-white rounded">

        <div class="card-header">
          <%= link_to user.username, user %>
        </div>

        <div class="card-body">

          <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>

          <p class="card-text">
          <%= pluralize(user.articles.count, "article") %>
          </p>
          <%= link_to 'View profile', user_path(user), class: "btn btn-outline-primary" %>

          <% if logged_in? && user == current_user %>
            <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info" %>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "DELETE ACCOUNT", user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg shadow-sm rounded" %>
          <% end %>


        </div>

        <div class="card-footer text-muted">
          <small>
            Joined <%= time_ago_in_words(user.created_at) %> ago
          </small>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Edit your profile</h1>
  <%= render 'form' %>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Bloggers on Rails</h1>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
  <%= render 'users' %>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4">Sign Up for Blog On Rails</h1>
  <small><h4 class="text-center mt-4">Signin up will let you create new artices!</h4></small>
  <%= render 'form' %>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>
  <%= gravatar_for @user, size: 200 %>
  <% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
      <%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-outline-info"%>
    </div> 
  <% end %>
  <% if logged_in? && current_user.admin? %>
    <div class="container" id="new-button-container">
      <div class="row justify-content-md-center">
        <div class="mt-4">
          <%= link_to "DELETE ACCOUNT", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-lg shadow-sm rounded" %>
        </div>
      </div>
    </div>
  <% end %>
  <h3 class="text-center mt-4">Articles</h3>
  <% if logged_in? && @user == current_user %>
    <div class="container" id="new-button-container">
      <div class="row justify-content-md-center">
        <div class="mt-4">
          <%= link_to 'NEW', new_article_path(), class: "btn btn-success btn-lg shadow-sm rounded"%>
        </div>
      </div>
    </div>
  <% end %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</body>
</html>